# Generated by Django 5.1.3 on 2024-12-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='en_name',
        ),
    ]
