# Generated by Django 5.1.3 on 2024-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_foods_en_description_remove_foods_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
