# Generated by Django 5.1.3 on 2024-12-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_categories_en_name'),
        ('foods', '0003_alter_foods_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
        migrations.AlterField(
            model_name='foods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='categories.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(verbose_name='Описание (англ.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.FileField(upload_to='static/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='ru_description',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='ru_name',
            field=models.CharField(max_length=100, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
