# Generated by Django 5.1.3 on 2024-12-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_foods_options_alter_foods_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(verbose_name='Описание (узб.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (узбс.)'),
        ),
    ]
