# Generated by Django 5.1.3 on 2024-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_foods_description_alter_foods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название (узб.)'),
        ),
    ]
