# Generated by Django 5.1.3 on 2024-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_foods_article_foods_weight_alter_foods_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='compound',
            field=models.TextField(default='1', verbose_name='Состав (узб.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='ru_compound',
            field=models.TextField(default='1', verbose_name='Состав (рус.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(verbose_name='Описание (узб.)'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='ru_description',
            field=models.TextField(verbose_name='Описание (рус.)'),
        ),
    ]
