# Generated by Django 5.1.3 on 2024-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_foods_compound_foods_ru_compound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Кетма-кетлик'),
        ),
    ]
