# Generated by Django 5.1.3 on 2024-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_foods_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='sequence_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Кетма-кетлик'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='Вес'),
        ),
    ]
