# Generated by Django 5.1.3 on 2024-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('готовится', 'готовится'), ('доставляется', 'доставляется'), ('yetkazib berildi', 'Yetkazib berildi'), ('доставленный', 'доставленный')], default='kutilmoqda', max_length=20, verbose_name='Статус'),
        ),
    ]
