# Generated by Django 5.1.3 on 2024-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('готовится', 'готовится'), ('доставляется', 'доставляется'), ('доставленный', 'доставленный'), ('отменен', 'отменен')], default='готовится', max_length=20, verbose_name='Статус'),
        ),
    ]
