# Generated by Django 5.1.3 on 2024-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_alter_telegramusers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Идентификатор чата'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='language',
            field=models.CharField(choices=[('ru', 'Ru'), ('uz', 'Uz')], default='uz', max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
