# Generated by Django 5.1.3 on 2024-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Кетма-кетлик'),
        ),
    ]
