back_main_menu = "Asosiy menu🏠"
back_main_menu_ru = "Главное меню🏠"
back_main_menu_en = "Main menu🏠"
adverts = "Reklama 📨"
forward_advert = "Forward 📥"
none_advert = "Oddiy 📥"
uz_language = "🇺🇿 O'zbek"
ru_language = "🇷🇺 Русский"
en_language = "🇬🇧 English"
choice_language = "Tilni o'zgartirish 🌐"
choice_language_ru = "Изменить язык 🌐"
choice_language_en = "Change language 🌐"
contact = 'Aloqa ☎️'
contact_ru = 'Контакты ☎️'
contact_en = 'Contact ☎️'
ask_question = 'Talab va Istaklar 💡'
ask_question_ru = 'Спрос и желание 💡'
ask_question_en = 'Demand and Wants 💡'
change_phone = "Telefon raqamini o'zgartirish 📱"
change_phone_ru = "Изменить номер телефона 📱"
change_phone_en = "Change phone number 📱"
