back_main_menu = "Asosiy menu🏠"
back_main_menu_ru = "Главное меню🏠"
adverts = "Reklama 📨"
forward_advert = "Forward 📥"
none_advert = "Oddiy 📥"
uz_language = "🇺🇿 O'zbek"
ru_language = "🇷🇺 Русский"
choice_language = "Tilni o'zgartirish 🌐"
choice_language_ru = "Изменить язык 🌐"
contact = 'Aloqa ☎️'
contact_ru = 'Контакты ☎️'
ask_question = 'Kompaniya haqida 💡'
ask_question_ru = 'О компании 💡'
change_phone = "Telefon raqamini o'zgartirish 📱"
change_phone_ru = "Изменить номер телефона 📱"
send_location = "Lokatsiya yuborish"
send_location_ru = "Отправить местоположение"
ordering = "🛍 Buyurtma berish"
ordering_ru = "🛍 Сделать заказ"
basket = "📥 Savat"
basket_ru = "📥 Корзина"
to_back = "⬅️ Orqaga"
to_back_ru = "⬅️ Назад"
